"use client"

import { motion } from 'framer-motion'
import { useInView } from 'framer-motion'
import { useRef } from 'react'
import { Users, TrendingUp, Award, Heart, Star, Quote } from 'lucide-react'

const ImpactTestimonials = () => {
  const ref = useRef(null)
  const isInView = useInView(ref, { once: true })

  const impactStats = [
    {
      number: "100",
      label: "Youths Empowered",
      description: "Per cohort, twice annually"
    },
    {
      number: "200",
      label: "Jobs Created",
      description: "Through participant businesses"
    },
    {
      number: "$500K",
      label: "Economic Impact",
      description: "Generated by participant ventures"
    },
    {
      number: "15",
      label: "Communities Served",
      description: "Across Liberia"
    }
  ]

  const testimonials = [
    {
      name: "Sarah Johnson",
      role: "Tech Entrepreneur",
      image: "👩‍💻",
      quote: "The 100 program transformed my life. I went from having no business experience to running a successful software development company that employs 5 people. The mentorship and mini-grant were game-changers.",
      rating: 5,
      achievement: "Founded TechLib Solutions"
    },
    {
      name: "Michael Doe",
      role: "Marketing Specialist",
      image: "👨‍💼",
      quote: "The internship at Annita LLC gave me real-world experience that I couldn't get anywhere else. I learned digital marketing, client management, and business development. Now I run my own agency.",
      rating: 5,
      achievement: "Launched Digital Marketing Agency"
    },
    {
      name: "Grace Williams",
      role: "Business Consultant",
      image: "👩‍🏫",
      quote: "As an affiliate, I earned while learning. The program taught me sales, networking, and business strategy. Today, I help other entrepreneurs start and grow their businesses.",
      rating: 5,
      achievement: "Established Consulting Firm"
    },
    {
      name: "David Kollie",
      role: "Agriculture Entrepreneur",
      image: "👨‍🌾",
      quote: "The mini-grant helped me start my organic farming business. The program's focus on sustainable business practices and community impact aligned perfectly with my vision.",
      rating: 5,
      achievement: "Started Organic Farm"
    },
    {
      name: "Fatima Kamara",
      role: "Healthcare Innovator",
      image: "👩‍⚕️",
      quote: "The 100 program connected me with mentors in the healthcare industry. Their guidance helped me develop a mobile health app that serves rural communities in Liberia.",
      rating: 5,
      achievement: "Developed Health App"
    },
    {
      name: "Emmanuel Bassa",
      role: "Education Entrepreneur",
      image: "👨‍🎓",
      quote: "I used the skills from The 100 to start an online learning platform. The program's emphasis on digital skills and innovation was exactly what I needed to succeed.",
      rating: 5,
      achievement: "Created Online Learning Platform"
    }
  ]

  const partnerTestimonials = [
    {
      name: "Liberia Bank for Development and Investment",
      representative: "John Smith, CEO",
      quote: "Partnering with The 100 has been incredibly rewarding. We've seen firsthand how our funding and mentorship have helped young entrepreneurs create sustainable businesses that contribute to Liberia's economic growth.",
      impact: "Funded 25 mini-grants"
    },
    {
      name: "Liberia Chamber of Commerce",
      representative: "Mary Johnson, President",
      quote: "The 100 program is exactly what Liberia needs. By providing comprehensive training and real-world experience, it's creating a new generation of business leaders who will drive our country's development.",
      impact: "Provided 50+ mentors"
    }
  ]

  return (
    <section className="py-16 sm:py-20" ref={ref}>
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8 }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-gray-900 mb-6">
              <span className="text-orange-600">Impact</span> & Testimonials
            </h2>
            <p className="text-lg sm:text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed">
              See the real impact of The 100 initiative through the success stories of our participants 
              and the testimonials of our partners. Every story represents a life transformed and 
              a community strengthened.
            </p>
          </motion.div>

          {/* Impact Statistics */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="mb-16"
          >
            <h3 className="text-2xl sm:text-3xl font-bold text-gray-900 text-center mb-12">
              Our Impact
            </h3>
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-6">
              {impactStats.map((stat, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  animate={isInView ? { opacity: 1, y: 0 } : {}}
                  transition={{ duration: 0.6, delay: 0.4 + index * 0.1 }}
                  className="bg-white p-6 rounded-xl shadow-lg border border-gray-100 text-center"
                >
                  <div className="text-3xl sm:text-4xl font-bold text-orange-600 mb-2">{stat.number}</div>
                  <div className="text-lg font-semibold text-gray-900 mb-1">{stat.label}</div>
                  <div className="text-sm text-gray-600">{stat.description}</div>
                </motion.div>
              ))}
            </div>
          </motion.div>

          {/* Expected Impact */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.6 }}
            className="mb-16"
          >
            <h3 className="text-2xl sm:text-3xl font-bold text-gray-900 text-center mb-12">
              Expected Impact Over 5 Years
            </h3>
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
              <div className="bg-gradient-to-br from-orange-500 to-orange-600 p-8 rounded-2xl text-white">
                <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center mb-6">
                  <Users className="w-6 h-6 text-white" />
                </div>
                <h4 className="text-2xl font-bold mb-4">1,000+ Youths Empowered</h4>
                <ul className="space-y-3 text-orange-100">
                  <li>• 10 cohorts of 100 participants each</li>
                  <li>• Comprehensive business training</li>
                  <li>• Hands-on experience and mentorship</li>
                  <li>• Access to funding and resources</li>
                </ul>
              </div>
              <div className="bg-gradient-to-br from-blue-500 to-blue-600 p-8 rounded-2xl text-white">
                <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center mb-6">
                  <TrendingUp className="w-6 h-6 text-white" />
                </div>
                <h4 className="text-2xl font-bold mb-4">$5M+ Economic Impact</h4>
                <ul className="space-y-3 text-blue-100">
                  <li>• 500+ new businesses created</li>
                  <li>• 2,000+ jobs generated</li>
                  <li>• Increased local economic activity</li>
                  <li>• Community development initiatives</li>
                </ul>
              </div>
              <div className="bg-gradient-to-br from-green-500 to-green-600 p-8 rounded-2xl text-white">
                <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center mb-6">
                  <Heart className="w-6 h-6 text-white" />
                </div>
                <h4 className="text-2xl font-bold mb-4">50+ Communities Served</h4>
                <ul className="space-y-3 text-green-100">
                  <li>• Nationwide program coverage</li>
                  <li>• Rural and urban development</li>
                  <li>• Cross-sector collaboration</li>
                  <li>• Sustainable community growth</li>
                </ul>
              </div>
            </div>
          </motion.div>

          {/* Participant Testimonials */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 0.8 }}
            className="mb-16"
          >
            <h3 className="text-2xl sm:text-3xl font-bold text-gray-900 text-center mb-12">
              Success Stories
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {testimonials.map((testimonial, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, y: 20 }}
                  animate={isInView ? { opacity: 1, y: 0 } : {}}
                  transition={{ duration: 0.6, delay: 1.0 + index * 0.1 }}
                  className="bg-white p-6 rounded-xl shadow-lg border border-gray-100"
                >
                  <div className="flex items-center mb-4">
                    <div className="text-3xl mr-4">{testimonial.image}</div>
                    <div>
                      <h4 className="text-lg font-semibold text-gray-900">{testimonial.name}</h4>
                      <p className="text-orange-600 font-medium text-sm">{testimonial.role}</p>
                    </div>
                  </div>
                  <div className="flex items-center mb-3">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <Star key={i} className="w-4 h-4 text-yellow-400 fill-current" />
                    ))}
                  </div>
                  <blockquote className="text-gray-700 text-sm mb-4 italic">
                    "{testimonial.quote}"
                  </blockquote>
                  <div className="bg-orange-50 p-3 rounded-lg">
                    <p className="text-orange-700 font-semibold text-sm">{testimonial.achievement}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>

          {/* Partner Testimonials */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 1.4 }}
            className="mb-16"
          >
            <h3 className="text-2xl sm:text-3xl font-bold text-gray-900 text-center mb-12">
              Partner Testimonials
            </h3>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              {partnerTestimonials.map((testimonial, index) => (
                <motion.div
                  key={index}
                  initial={{ opacity: 0, x: index % 2 === 0 ? -30 : 30 }}
                  animate={isInView ? { opacity: 1, x: 0 } : {}}
                  transition={{ duration: 0.8, delay: 1.6 + index * 0.2 }}
                  className="bg-gradient-to-br from-gray-50 to-white p-8 rounded-2xl border border-gray-200"
                >
                  <div className="flex items-start space-x-4 mb-6">
                    <div className="w-12 h-12 bg-orange-100 rounded-xl flex items-center justify-center flex-shrink-0">
                      <Quote className="w-6 h-6 text-orange-600" />
                    </div>
                    <div>
                      <h4 className="text-lg font-semibold text-gray-900">{testimonial.name}</h4>
                      <p className="text-orange-600 font-medium text-sm">{testimonial.representative}</p>
                    </div>
                  </div>
                  <blockquote className="text-gray-700 mb-4 italic leading-relaxed">
                    "{testimonial.quote}"
                  </blockquote>
                  <div className="bg-orange-100 p-3 rounded-lg inline-block">
                    <p className="text-orange-700 font-semibold text-sm">{testimonial.impact}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>

          {/* Community Impact */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 1.8 }}
            className="mb-16"
          >
            <h3 className="text-2xl sm:text-3xl font-bold text-gray-900 text-center mb-12">
              Community Impact
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="bg-white p-8 rounded-2xl shadow-lg border border-gray-100">
                <div className="w-12 h-12 bg-green-100 rounded-xl flex items-center justify-center mb-6">
                  <Award className="w-6 h-6 text-green-600" />
                </div>
                <h4 className="text-xl font-semibold text-gray-900 mb-4">Economic Development</h4>
                <ul className="space-y-3 text-gray-700">
                  <li>• New businesses create local employment</li>
                  <li>• Increased economic activity in communities</li>
                  <li>• Reduced youth unemployment rates</li>
                  <li>• Improved standard of living for families</li>
                </ul>
              </div>
              <div className="bg-white p-8 rounded-2xl shadow-lg border border-gray-100">
                <div className="w-12 h-12 bg-blue-100 rounded-xl flex items-center justify-center mb-6">
                  <Heart className="w-6 h-6 text-blue-600" />
                </div>
                <h4 className="text-xl font-semibold text-gray-900 mb-4">Social Impact</h4>
                <ul className="space-y-3 text-gray-700">
                  <li>• Youth become role models in communities</li>
                  <li>• Knowledge transfer to other community members</li>
                  <li>• Increased community pride and engagement</li>
                  <li>• Sustainable development practices</li>
                </ul>
              </div>
            </div>
          </motion.div>

          {/* Call to Action */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, delay: 2.0 }}
            className="text-center bg-gradient-to-r from-orange-500 to-orange-600 rounded-2xl p-8 text-white"
          >
            <h3 className="text-2xl sm:text-3xl font-bold mb-4">
              Be Part of the Impact
            </h3>
            <p className="text-orange-100 mb-6 max-w-2xl mx-auto">
              Join The 100 initiative and become part of a movement that's transforming 
              lives and communities across Liberia. Your success story could be next.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <button className="bg-white text-orange-600 px-8 py-3 rounded-lg font-semibold hover:bg-orange-50 transition-colors duration-200">
                Apply Now
              </button>
              <button className="border-2 border-white text-white px-8 py-3 rounded-lg font-semibold hover:bg-white hover:text-orange-600 transition-colors duration-200">
                Partner With Us
              </button>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  )
}

export default ImpactTestimonials
